// <auto-generated>
//   Generated by XOOP Compiler v1.0.0
//   Do not edit this file manually — edit the .xoop source instead.
// </auto-generated>

using System;
using System.Collections.Generic;


    public interface ISpeakable
    {
        void Speak();

        string GetSound();
    }

    public enum AnimalKind
    {
        Unknown = 0,
        Dog,
        Cat,
        Bird
    }

    public abstract class Animal : ISpeakable
    {
        private readonly string _name;
        protected string _sound;

        public string Name
        {
            get => _name;
        }

        public Animal(string name, string sound)
        {
            _name  = name;
            _sound = sound;
        }

        public virtual string GetSound()
        {
            return _sound;
        }

        public virtual void Speak()
        {
            Console.WriteLine($"{_name} says: {_sound}!");
        }

        public abstract AnimalKind Kind();

        public override string ToString()
        {
            return $"{Kind()} named '{_name}'";
        }
    }

    public class Dog : Animal
    {
        public Dog(string name) : base(name, "Woof")
        {
        }

        public void Fetch()
        {
            Console.WriteLine($"{Name} fetches the ball!");
        }

        public override AnimalKind Kind()
        {
            return AnimalKind.Dog;
        }
    }

    public class Cat : Animal
    {
        public Cat(string name) : base(name, "Meow")
        {
        }

        public void Purr()
        {
            Console.WriteLine($"{Name} purrs contentedly~");
        }

        public override AnimalKind Kind()
        {
            return AnimalKind.Cat;
        }
    }

    public class Bird : Animal
    {
        private readonly bool _canFly;

        public bool CanFly
        {
            get => _canFly;
        }

        public Bird(string name, bool canFly = true) : base(name, "Tweet")
        {
            _canFly = canFly;
        }

        public override AnimalKind Kind()
        {
            return AnimalKind.Bird;
        }

        public override void Speak()
        {
            Console.Write($"{Name} chirps: Tweet!");
            Console.WriteLine(CanFly ? "  *flutters away*" : "  (flightless)");
        }
    }

    public static class Program
    {
        public static void Main(string[] args)
        {
            var animals = new List<Animal>
            {
                new Dog("Rex"),
                new Dog("Buddy"),
                new Cat("Whiskers"),
                new Bird("Tweety"),
                new Bird("Penguin", false),
            };

            Console.WriteLine("=== Animal Kingdom ===");
            foreach (var animal in animals)
            {
                animal.Speak();
                Console.WriteLine($"   -> {animal}");
            }

            Console.WriteLine();
            Console.WriteLine("=== Dog Tricks ===");
            var dog = new Dog("Max");
            dog.Speak();
            dog.Fetch();

            Console.WriteLine();
            Console.WriteLine("=== Cat Corner ===");
            var cat = new Cat("Luna");
            cat.Speak();
            cat.Purr();
        }
    }

Program.Main(null);