// <auto-generated>
//   Generated by XOOP Compiler v1.0.0
//   Do not edit this file manually — edit the .xoop source instead.
// </auto-generated>

using System;

namespace Hello
{
    public class Greeter
    {
        private readonly string _greeting = "Hello";

        public Greeter(string greeting = "Hello")
        {
            _greeting = greeting;
        }

        public void Greet(string name)
        {
            Console.WriteLine($"{_greeting}, {name}!");
        }
    }

    public static class Program
    {
        public static void Main(string[] args)
        {
            var greeter = new Greeter();
            greeter.Greet("World");
            greeter.Greet("XOOP");

            var custom = new Greeter("Howdy");
            custom.Greet("partner");
        }
    }
}
