using System.Text;
using Xoop.AST;

namespace Xoop.Emitter;

public class CSharpEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private const string IndentUnit = "    ";

    // ── Entry ─────────────────────────────────────────────────────────────────

    public string Emit(ProgramNode program)
    {
        _sb.Clear();
        _indent = 0;

        _sb.AppendLine("// <auto-generated>");
        _sb.AppendLine("//   Generated by XOOP Compiler v1.0.0");
        _sb.AppendLine("//   Do not edit this file manually — edit the .xoop source instead.");
        _sb.AppendLine("// </auto-generated>");
        _sb.AppendLine();

        foreach (var u in program.Usings) _sb.AppendLine($"using {u};");
        if (program.Usings.Any()) _sb.AppendLine();

        bool gap = false;

        foreach (var en  in program.TopLevelEnums)      { if (gap) _sb.AppendLine(); EmitEnum(en);      gap = true; }
        foreach (var ifc in program.TopLevelInterfaces) { if (gap) _sb.AppendLine(); EmitInterface(ifc); gap = true; }
        foreach (var cls in program.TopLevelClasses)    { if (gap) _sb.AppendLine(); EmitClass(cls);     gap = true; }
        foreach (var ns  in program.Namespaces)         { if (gap) _sb.AppendLine(); EmitNamespace(ns);  gap = true; }

        return _sb.ToString();
    }

    // ── Namespace ─────────────────────────────────────────────────────────────

    private void EmitNamespace(NamespaceNode ns)
    {
        Line($"namespace {ns.Name}");
        Line("{");
        _indent++;

        bool gap = false;
        foreach (var ifc in ns.Interfaces) { if (gap) _sb.AppendLine(); EmitInterface(ifc); gap = true; }
        foreach (var en  in ns.Enums)      { if (gap) _sb.AppendLine(); EmitEnum(en);       gap = true; }
        foreach (var cls in ns.Classes)    { if (gap) _sb.AppendLine(); EmitClass(cls);      gap = true; }

        _indent--;
        Line("}");
    }

    // ── Class ─────────────────────────────────────────────────────────────────

    private void EmitClass(ClassNode cls)
    {
        var mods     = Mods(cls.Access, isStatic: cls.IsStatic, isAbstract: cls.IsAbstract,
                                        isSealed:  cls.IsSealed,  isPartial:  cls.IsPartial);
        var generics = GenericList(cls.GenericParams);
        var bases    = BaseList(cls.BaseClass, cls.Interfaces);

        Line($"{mods}class {cls.Name}{generics}{bases}");
        Line("{");
        _indent++;

        bool gap = false;

        // Fields
        foreach (var f in cls.Fields)        { EmitField(f);       gap = true; }

        // Properties — blank line between each, and before first if fields exist
        foreach (var p in cls.Properties)    { if (gap) _sb.AppendLine(); EmitProperty(p); gap = true; }

        // Constructors
        foreach (var c in cls.Constructors)  { if (gap) _sb.AppendLine(); EmitConstructor(c, cls.Name); gap = true; }

        // Methods
        foreach (var m in cls.Methods)       { if (gap) _sb.AppendLine(); EmitMethod(m); gap = true; }

        // Nested enums + classes
        foreach (var ne in cls.NestedEnums)  { if (gap) _sb.AppendLine(); EmitEnum(ne);  gap = true; }
        foreach (var nc in cls.NestedClasses){ if (gap) _sb.AppendLine(); EmitClass(nc); gap = true; }

        _indent--;
        Line("}");
    }

    // ── Interface ─────────────────────────────────────────────────────────────

    private void EmitInterface(InterfaceNode iface)
    {
        var ext = iface.Extends.Any() ? " : " + string.Join(", ", iface.Extends) : "";
        Line($"{iface.Access} interface {iface.Name}{ext}");
        Line("{");
        _indent++;

        bool gap = false;

        foreach (var p in iface.Properties)
        {
            var acc = (p.HasGet ? "get; " : "") + (p.HasSet ? "set; " : "");
            Line($"{p.Type} {p.Name} {{ {acc.TrimEnd()} }}");
            gap = true;
        }

        foreach (var m in iface.Methods)
        {
            if (gap) _sb.AppendLine();
            Line($"{m.ReturnType} {m.Name}({Params(m.Parameters)});");
            gap = true;
        }

        _indent--;
        Line("}");
    }

    // ── Enum ──────────────────────────────────────────────────────────────────

    private void EmitEnum(EnumNode en)
    {
        var underlying = en.UnderlyingType != null ? $" : {en.UnderlyingType}" : "";
        Line($"{en.Access} enum {en.Name}{underlying}");
        Line("{");
        _indent++;

        for (int i = 0; i < en.Members.Count; i++)
        {
            var m     = en.Members[i];
            var value = m.Value != null ? $" = {m.Value}" : "";
            var comma = i < en.Members.Count - 1 ? "," : "";
            Line($"{m.Name}{value}{comma}");
        }

        _indent--;
        Line("}");
    }

    // ── Field ─────────────────────────────────────────────────────────────────

    private void EmitField(FieldNode f)
    {
        var mods = Mods(f.Access, isStatic: f.IsStatic,
                                  isConst:    f.IsConst,
                                  isReadOnly: f.IsReadOnly && !f.IsConst);
        var init = f.DefaultValue != null ? $" = {f.DefaultValue}" : "";
        Line($"{mods}{f.Type} {f.Name}{init};");
    }

    // ── Property ──────────────────────────────────────────────────────────────

    private void EmitProperty(PropertyNode p)
    {
        var mods = Mods(p.Access, isStatic: p.IsStatic, isVirtual: p.IsVirtual, isOverride: p.IsOverride);

        // ── Custom body (<Get> / <Set> children) ──────────────────────────────
        if (p.GetBody != null || p.SetBody != null)
        {
            Line($"{mods}{p.Type} {p.Name}");
            Line("{");
            _indent++;

            if (p.HasGet && p.GetBody != null)
            {
                Line("get");
                Line("{");
                _indent++; EmitBody(p.GetBody); _indent--;
                Line("}");
            }
            if (p.HasSet && p.SetBody != null)
            {
                var sm = p.SetAccess != "" ? $"{p.SetAccess} " : "";
                Line($"{sm}set");
                Line("{");
                _indent++; EmitBody(p.SetBody); _indent--;
                Line("}");
            }

            _indent--;
            Line("}");
            return;
        }

        // ── Field-backed property (fieldRef="...") ────────────────────────────
        if (p.FieldRef != null)
        {
            Line($"{mods}{p.Type} {p.Name}");
            Line("{");
            _indent++;

            if (p.HasGet) Line($"get => {p.FieldRef};");
            if (p.HasSet)
            {
                var sm = p.SetAccess != "" ? $"{p.SetAccess} " : "";
                Line($"{sm}set => {p.FieldRef} = value;");
            }

            _indent--;
            Line("}");
            return;
        }

        // ── Auto-property ─────────────────────────────────────────────────────
        {
            var accessors = new List<string>();
            if (p.HasGet) accessors.Add("get;");
            if (p.HasSet)
            {
                var sm = p.SetAccess != "" ? $"{p.SetAccess} " : "";
                accessors.Add($"{sm}set;");
            }
            var init = p.DefaultValue != null ? $" = {p.DefaultValue};" : "";
            Line($"{mods}{p.Type} {p.Name} {{ {string.Join(" ", accessors)} }}{init}");
        }
    }

    // ── Constructor ───────────────────────────────────────────────────────────

    private void EmitConstructor(ConstructorNode c, string className)
    {
        var baseCall = c.BaseCallArgs != null
            ? $" : {(c.IsThisCall ? "this" : "base")}({c.BaseCallArgs})"
            : "";

        Line($"{c.Access} {className}({Params(c.Parameters)}){baseCall}");
        Line("{");
        _indent++;
        EmitBody(c.Body);
        _indent--;
        Line("}");
    }

    // ── Method ────────────────────────────────────────────────────────────────

    private void EmitMethod(MethodNode m)
    {
        var mods     = Mods(m.Access, isStatic: m.IsStatic, isAbstract: m.IsAbstract,
                                      isVirtual: m.IsVirtual, isOverride: m.IsOverride,
                                      isSealed:  m.IsSealed,  isNew:      m.IsNew,
                                      isAsync:   m.IsAsync);
        var generics = GenericList(m.GenericParams);
        var parms    = Params(m.Parameters);

        if (m.IsAbstract)
        {
            Line($"{mods}{m.ReturnType} {m.Name}{generics}({parms});");
            return;
        }

        Line($"{mods}{m.ReturnType} {m.Name}{generics}({parms})");
        Line("{");
        _indent++;
        EmitBody(m.Body);
        _indent--;
        Line("}");
    }

    // ── Body ─────────────────────────────────────────────────────────────────

    private void EmitBody(string body)
    {
        var lines = body.Split('\n').Select(l => l.TrimEnd()).ToList();

        // strip leading / trailing blank lines
        while (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[0]))    lines.RemoveAt(0);
        while (lines.Count > 0 && string.IsNullOrWhiteSpace(lines[^1]))   lines.RemoveAt(lines.Count - 1);
        if (lines.Count == 0) return;

        // detect & strip common leading whitespace (handles CDATA indentation)
        int minPad = lines
            .Where(l => !string.IsNullOrWhiteSpace(l))
            .Select(l => l.Length - l.TrimStart().Length)
            .DefaultIfEmpty(0).Min();

        foreach (var raw in lines)
        {
            if (string.IsNullOrWhiteSpace(raw)) { _sb.AppendLine(); continue; }
            var stripped = raw.Length > minPad ? raw[minPad..] : raw.TrimStart();
            Indent();
            _sb.AppendLine(stripped);
        }
    }

    // ── Low-level helpers ─────────────────────────────────────────────────────

    private void Line(string text)   { Indent(); _sb.AppendLine(text); }
    private void Indent()             { for (int i = 0; i < _indent; i++) _sb.Append(IndentUnit); }

    private static string GenericList(List<string> g) =>
        g.Count > 0 ? $"<{string.Join(", ", g)}>" : "";

    private static string BaseList(string? baseClass, List<string> ifaces)
    {
        var parts = new List<string>();
        if (baseClass != null) parts.Add(baseClass);
        parts.AddRange(ifaces);
        return parts.Count > 0 ? " : " + string.Join(", ", parts) : "";
    }

    private static string Params(IEnumerable<ParameterNode> parameters) =>
        string.Join(", ", parameters.Select(p =>
        {
            var prefix = p.IsParams ? "params " : p.IsRef ? "ref " : p.IsOut ? "out " : p.IsIn ? "in " : "";
            var def    = p.DefaultValue != null ? $" = {p.DefaultValue}" : "";
            return $"{prefix}{p.Type} {p.Name}{def}";
        }));

    private static string Mods(
        string access,
        bool isStatic   = false,
        bool isAbstract = false,
        bool isVirtual  = false,
        bool isOverride = false,
        bool isSealed   = false,
        bool isNew      = false,
        bool isAsync    = false,
        bool isPartial  = false,
        bool isConst    = false,
        bool isReadOnly = false)
    {
        var parts = new List<string> { access };
        if (isStatic)   parts.Add("static");
        if (isConst)    parts.Add("const");
        if (isReadOnly) parts.Add("readonly");
        if (isAbstract) parts.Add("abstract");
        if (isVirtual)  parts.Add("virtual");
        if (isOverride) parts.Add("override");
        if (isSealed)   parts.Add("sealed");
        if (isNew)      parts.Add("new");
        if (isAsync)    parts.Add("async");
        if (isPartial)  parts.Add("partial");
        return string.Join(" ", parts) + " ";
    }
}
